// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function BrowseForFile():Promise<string>;

export function CheckForUpdates():Promise<models.UpdateInfo>;

export function GetDataDirectory():Promise<string>;

export function CreateContact(arg1:models.Contact):Promise<models.Contact>;

export function CreateDocument(arg1:models.Document):Promise<models.Document>;

export function CreateExpense(arg1:models.Expense):Promise<models.Expense>;

export function CreateMaintenanceRequest(arg1:models.MaintenanceRequest):Promise<models.MaintenanceRequest>;

export function CreatePayment(arg1:models.Payment):Promise<models.Payment>;

export function CreateReminder(arg1:models.Reminder):Promise<models.Reminder>;

export function CreateTenant(arg1:models.Tenant):Promise<models.Tenant>;

export function DeleteContact(arg1:number):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function OpenDocument(arg1:number):Promise<void>;

export function DeleteExpense(arg1:number):Promise<void>;

export function DeleteMaintenanceRequest(arg1:number):Promise<void>;

export function DeletePayment(arg1:number):Promise<void>;

export function DeleteReminder(arg1:number):Promise<void>;

export function DeleteTenant(arg1:number):Promise<void>;

export function DismissReminder(arg1:number):Promise<void>;

export function GetContact(arg1:number):Promise<models.Contact>;

export function GetContacts():Promise<Array<models.Contact>>;

export function GetDashboardData():Promise<services.DashboardData>;

export function GetDocument(arg1:number):Promise<models.Document>;

export function GetDocuments(arg1:string):Promise<Array<models.Document>>;

export function GetExpense(arg1:number):Promise<models.Expense>;

export function GetExpenseSummary(arg1:number):Promise<models.ExpenseSummary>;

export function GetExpenses(arg1:string,arg2:number):Promise<Array<models.Expense>>;

export function GetMaintenanceRequest(arg1:number):Promise<models.MaintenanceRequest>;

export function GetMaintenanceRequests(arg1:string):Promise<Array<models.MaintenanceRequest>>;

export function GetPayment(arg1:number):Promise<models.Payment>;

export function GetPaymentSummary(arg1:number,arg2:number):Promise<models.PaymentSummary>;

export function GetPayments(arg1:number,arg2:number,arg3:number):Promise<Array<models.Payment>>;

export function GetProperty():Promise<models.Property>;

export function GetRecentActivity(arg1:number):Promise<Array<models.ActivityLog>>;

export function GetReminders(arg1:boolean):Promise<Array<models.Reminder>>;

export function GetTenant(arg1:number):Promise<models.Tenant>;

export function GetTenants(arg1:string):Promise<Array<models.Tenant>>;

export function GetUpcomingReminders(arg1:number):Promise<Array<models.Reminder>>;

export function UpdateContact(arg1:models.Contact):Promise<void>;

export function UpdateExpense(arg1:models.Expense):Promise<void>;

export function UpdateMaintenanceRequest(arg1:models.MaintenanceRequest):Promise<void>;

export function UpdatePayment(arg1:models.Payment):Promise<void>;

export function UpdateProperty(arg1:models.Property):Promise<void>;

export function UpdateReminder(arg1:models.Reminder):Promise<void>;

export function UpdateTenant(arg1:models.Tenant):Promise<void>;
