// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForFile() {
  return window['go']['main']['App']['BrowseForFile']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function GetDataDirectory() {
  return window['go']['main']['App']['GetDataDirectory']();
}

export function CreateContact(arg1) {
  return window['go']['main']['App']['CreateContact'](arg1);
}

export function CreateDocument(arg1) {
  return window['go']['main']['App']['CreateDocument'](arg1);
}

export function CreateExpense(arg1) {
  return window['go']['main']['App']['CreateExpense'](arg1);
}

export function CreateMaintenanceRequest(arg1) {
  return window['go']['main']['App']['CreateMaintenanceRequest'](arg1);
}

export function CreatePayment(arg1) {
  return window['go']['main']['App']['CreatePayment'](arg1);
}

export function CreateReminder(arg1) {
  return window['go']['main']['App']['CreateReminder'](arg1);
}

export function CreateTenant(arg1) {
  return window['go']['main']['App']['CreateTenant'](arg1);
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function GetDocumentContent(arg1) {
  return window['go']['main']['App']['GetDocumentContent'](arg1);
}

export function DeleteExpense(arg1) {
  return window['go']['main']['App']['DeleteExpense'](arg1);
}

export function DeleteMaintenanceRequest(arg1) {
  return window['go']['main']['App']['DeleteMaintenanceRequest'](arg1);
}

export function DeletePayment(arg1) {
  return window['go']['main']['App']['DeletePayment'](arg1);
}

export function DeleteReminder(arg1) {
  return window['go']['main']['App']['DeleteReminder'](arg1);
}

export function DeleteTenant(arg1) {
  return window['go']['main']['App']['DeleteTenant'](arg1);
}

export function DismissReminder(arg1) {
  return window['go']['main']['App']['DismissReminder'](arg1);
}

export function GetContact(arg1) {
  return window['go']['main']['App']['GetContact'](arg1);
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetDashboardData() {
  return window['go']['main']['App']['GetDashboardData']();
}

export function GetDocument(arg1) {
  return window['go']['main']['App']['GetDocument'](arg1);
}

export function GetDocuments(arg1) {
  return window['go']['main']['App']['GetDocuments'](arg1);
}

export function GetExpense(arg1) {
  return window['go']['main']['App']['GetExpense'](arg1);
}

export function GetExpenseSummary(arg1) {
  return window['go']['main']['App']['GetExpenseSummary'](arg1);
}

export function GetExpenses(arg1, arg2) {
  return window['go']['main']['App']['GetExpenses'](arg1, arg2);
}

export function GetMaintenanceRequest(arg1) {
  return window['go']['main']['App']['GetMaintenanceRequest'](arg1);
}

export function GetMaintenanceRequests(arg1) {
  return window['go']['main']['App']['GetMaintenanceRequests'](arg1);
}

export function GetPayment(arg1) {
  return window['go']['main']['App']['GetPayment'](arg1);
}

export function GetPaymentSummary(arg1, arg2) {
  return window['go']['main']['App']['GetPaymentSummary'](arg1, arg2);
}

export function GetPayments(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPayments'](arg1, arg2, arg3);
}

export function GetProperty() {
  return window['go']['main']['App']['GetProperty']();
}

export function GetRecentActivity(arg1) {
  return window['go']['main']['App']['GetRecentActivity'](arg1);
}

export function GetReminders(arg1) {
  return window['go']['main']['App']['GetReminders'](arg1);
}

export function GetTenant(arg1) {
  return window['go']['main']['App']['GetTenant'](arg1);
}

export function GetTenants(arg1) {
  return window['go']['main']['App']['GetTenants'](arg1);
}

export function GetUpcomingReminders(arg1) {
  return window['go']['main']['App']['GetUpcomingReminders'](arg1);
}

export function UpdateContact(arg1) {
  return window['go']['main']['App']['UpdateContact'](arg1);
}

export function UpdateExpense(arg1) {
  return window['go']['main']['App']['UpdateExpense'](arg1);
}

export function UpdateMaintenanceRequest(arg1) {
  return window['go']['main']['App']['UpdateMaintenanceRequest'](arg1);
}

export function UpdatePayment(arg1) {
  return window['go']['main']['App']['UpdatePayment'](arg1);
}

export function UpdateProperty(arg1) {
  return window['go']['main']['App']['UpdateProperty'](arg1);
}

export function UpdateReminder(arg1) {
  return window['go']['main']['App']['UpdateReminder'](arg1);
}

export function UpdateTenant(arg1) {
  return window['go']['main']['App']['UpdateTenant'](arg1);
}
